---
title: "In-class Exercise 7"
format: html
editor: visual
---

# 1. Getting Started 
Before getting start, make sure that ggHoriPlot has been included in the `pacman::p_load(...)` statement above.

```{r}
pacman::p_load(ggHoriPlot, ggthemes, tidyverse, lubridate)
```

# 2. Importing the Data

```{r}
averp <- read_csv("data/AVERP.csv") 
```

# 3. Data Wrangling

```{r}
averp <- averp %>%
  mutate(`Date` = dmy(`Date`))
```

# 4. Plotting the Horizon graph

```{r}
averp %>% 
  filter(Date >= "2018-01-01") %>%
  ggplot() +
  geom_horizon(aes(x = Date, y=Values), 
               origin = "midpoint", 
               horizonscale = 6)+
  facet_grid(`Consumer Items`~.) +
    theme_few() +
  scale_fill_hcl(palette = 'RdBu') +
  theme(panel.spacing.y=unit(0, "lines"), strip.text.y = element_text(
    size = 5, angle = 0, hjust = 0),
    legend.position = 'none',
    axis.text.y = element_blank(),
    axis.text.x = element_text(size=7),
    axis.title.y = element_blank(),
    axis.title.x = element_blank(),
    axis.ticks.y = element_blank(),
    panel.border = element_blank()
    ) +
    scale_x_date(expand=c(0,0), date_breaks = "3 month", date_labels = "%b%y") +
  ggtitle('Average Retail Prices of Selected Consumer Items (Jan 2018 to Dec 2022)')

```
